version: 2

project_name: goxsub

builds:
  - main: ./cmd/goxsub/
    binary: goxsub
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE

checksum:
  name_template: checksums.txt


changelog:
  sort: asc

release:
  github:
    owner: Arsolitt
    name: goxsub
